import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/" className="font-medium text-blue-600 dark:text-blue-500 hover:underline mr-6">
          サンプルコード
        </Link>
        <Link href="/other" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">
          useEffectだと難しいサンプルコード
        </Link>
        {children}
      </body>
    </html>
  )
}
